### ISSUE TITLE
Zooniverse use cases

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#109]
<table class="tg">
<thead>
  <tr>
    <th class="tg-fymr">Project</th>
    <th class="tg-7btt">Dataset</th>
    <th class="tg-fymr">Sampling algorithm</th>
    <th class="tg-fymr">Classification task(s)</th>
    <th class="tg-fymr">Launch Date</th>
    <th class="tg-fymr">URL</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">Marvin's pilot</td>
    <td class="tg-c3ow">LENA/BabyLogger data</td>
    <td class="tg-c3ow">i) for each recorded child, extract 10 sections of 30 seconds that are NOT silence (according to simple loudness detector) 
ii) cut these sections up into 500ms clips. NOTE : Loudness detector score should be averaged across LENA and BabyLogger </td>
    <td class="tg-c3ow">child voc, female adult speech, male adult speech, junk</td>
    <td class="tg-0pky">ASAP</td>
    <td class="tg-0pky">https://www.zooniverse.org/lab/14957 (if you can not access it, click "my projects" on the top left menu of zooniverse</td>
  </tr>
  <tr>
    <td class="tg-0pky">ERC WP1e/g</td>
    <td class="tg-0pky">"all"</td>
    <td class="tg-0pky">extract 350 vocs from CHI & FEM (vtc) for each recorded child, cut into 500ms (note: it would be good if the "skip/exclude" procedure would be in place)</td>
    <td class="tg-0pky">1) CHI/FEM/Junk; 2) if CHI or FEM, crying, laughing, canonical, non-canonical</td>
    <td class="tg-0pky">no rush</td>
    <td class="tg-0pky">doesn't exist yet</td>
  </tr>
  <tr>
    <td class="tg-0pky">zoo-phon (gold)</td>
    <td class="tg-0pky">1 pilot recording</td>
    <td class="tg-0pky">if there are enough, pull out 250 randomly & 250 from high child volubility 1-minute regions (the latter should be "consecutive vocs" ie take top minute and pull out all the vocs from there, then move to next minute, etc) - IS NOT chunkified!
</td>
    <td class="tg-0pky">NONE! will be annotated in the lab</td>
    <td class="tg-0pky">late Feb?</td>
    <td class="tg-0pky">(none)</td>
  </tr>
  <tr>
    <td class="tg-0pky">zoo-phon (pilot)</td>
    <td class="tg-0pky">same pilot rec as above</td>
    <td class="tg-0pky">same segments as above, but they are processed in different ways: 1. the usual 500ms chunks; 2. cut at provided list of boundaries (coded by human); 3. cut at provided list of boundaries (coded by machine) [NOTE: both lists are provided by collaborators] </td>
    <td class="tg-0pky">will be set up by collaborator, involves transcribing using the International Phonetic Alphabet</td>
    <td class="tg-0pky">probably in April</td>
    <td class="tg-0pky">(tbd by collaborator)</td>
  </tr>
  <tr>
    <td class="tg-0pky">zoo-phon</td>
    <td class="tg-0pky">10 randomly selected children from each of 5 corpora tbd</td>
    <td class="tg-0pky">depends on results of pilor, but will probably be based on user-provided list of segments & boundaries </td>
    <td class="tg-0pky">same as above</td>
    <td class="tg-0pky">probably in September</td>
    <td class="tg-0pky">(tbd by collaborator)</td>
  </tr>
</tbody>
</table>

**Comment by MarvinLvn** [comment]
Updated with my info :)

**Comment by alecristia** [comment]
Updated below

<table class="tg">
<thead>
  <tr>
    <th class="tg-fymr">Project</th>
    <th class="tg-7btt">Dataset</th>
    <th class="tg-fymr">Sampling algorithm</th>
    <th class="tg-fymr">Classification task(s)</th>
    <th class="tg-fymr">Launch Date</th>
    <th class="tg-fymr">URL</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">Marvin's pilot</td>
    <td class="tg-c3ow">LENA/BabyLogger data</td>
    <td class="tg-c3ow">i) for each recorded child, extract 10 sections of 30 seconds that are NOT silence (according to simple loudness detector) 
ii) cut these sections up into 500ms clips. NOTE : Loudness detector score should be averaged across LENA and BabyLogger </td>
    <td class="tg-c3ow">child voc, female adult speech, male adult speech, junk</td>
    <td class="tg-0pky">ASAP</td>
    <td class="tg-0pky">https://www.zooniverse.org/lab/14957 (if you can not access it, click "my projects" on the top left menu of zooniverse</td>
  </tr>
  <tr>
    <td class="tg-0pky">ERC WP1e/g</td>
    <td class="tg-0pky">"all"</td>
    <td class="tg-0pky">extract 350 vocs from CHI & FEM (vtc) for each recorded child, cut into 500ms (note: it would be good if the "skip/exclude" procedure would be in place)</td>
    <td class="tg-0pky">1) CHI/FEM/Junk; 2) if CHI or FEM, crying, laughing, canonical, non-canonical</td>
    <td class="tg-0pky">no rush</td>
    <td class="tg-0pky">doesn't exist yet</td>
  </tr>
  <tr>
    <td class="tg-0pky">zoo-phon (gold)</td>
    <td class="tg-0pky">1 pilot recording</td>
    <td class="tg-0pky">if there are enough, pull out 250 randomly & 250 from high child volubility 1-minute regions (the latter should be "consecutive vocs" ie take top minute and pull out all the vocs from there, then move to next minute, etc) - IS NOT chunkified!
</td>
    <td class="tg-0pky">NONE! will be annotated in the lab</td>
    <td class="tg-0pky">late Feb?</td>
    <td class="tg-0pky">(none)</td>
  </tr>
  <tr>
    <td class="tg-0pky">zoo-phon (pilot)</td>
    <td class="tg-0pky">same pilot rec as above</td>
    <td class="tg-0pky">same segments as above, but they are processed in different ways: 1. the usual 500ms chunks; 2. cut at provided list of boundaries (coded by human); 3. cut at provided list of boundaries (coded by machine) [NOTE: both lists are provided by collaborators] </td>
    <td class="tg-0pky">will be set up by collaborator, involves transcribing using the International Phonetic Alphabet</td>
    <td class="tg-0pky">probably in April</td>
    <td class="tg-0pky">(tbd by collaborator)</td>
  </tr>
  <tr>
    <td class="tg-0pky">zoo-phon</td>
    <td class="tg-0pky">10 randomly selected children from each of 5 corpora tbd</td>
    <td class="tg-0pky">depends on results of pilor, but will probably be based on user-provided list of segments & boundaries </td>
    <td class="tg-0pky">same as above</td>
    <td class="tg-0pky">probably in September</td>
    <td class="tg-0pky">(tbd by collaborator)</td>
  </tr>
</tbody>
</table>

**Comment by lucasgautheron** [comment]
This is the roadmap I suggest:

1. Define a flexible metadata format to store the information about the chunks. We are done (or almost) with that already, but we need to think this thoroughly to make it work in the long run
2. Implement "custom segments" support in `child-project zooniverse extract-chunks`. Thus, users can do then own magic for the sampling and use our tool for the extraction and upload of chunks anyway.
3. I'll write scripts to implement the most urgent sampler needs (e.g. @MarvinLvn's way) to be used altogether with `child-project zooniverse extract-chunks`.
4. If some of these procedures turn out to be standards / not too arbitrary, we can implement them into `child-project zooniverse extract-chunks`.

Does it sound good to you ?

**Comment by alecristia** [comment]
to clarify: 

for now, we implement a minimum within the package, and leave scripts for sampling outside of the package. Then, as these scripts get reused (or not) we make decisions of which to work into the package. Did I get that right?

If so, that sounds like an ideal approach -- instead of making decisions about what is likely or not, and then signing up to update code for those decisions, we have a period of observation in terms of what are the most common decisions.

**Comment by lucasgautheron** [comment]
Yep, exactly!
