### ISSUE TITLE
.cha importation support

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#114]
Alex:

> I was looking over the daylong vandam and realized that, actually, there are three types of annotation: .its, .rttm (generated by vtc over the course of corpus adaptation), and human, inside .cha file.
.cha is a very standard file in language acquisition, I think there could be packages we can rely on:
https://github.com/SeedlingsBabylab/pyclan
https://github.com/SeedlingsBabylab/parse_clan2
https://jacksonllee.com/papers/lee-etal-2016-pylangacq.pdf
This will probably increase interest, and would make this dataset also a good example for ChildRecordsR @alsonicr !

**Comment by lucasgautheron** [comment]
@alecristia do you want that in the first release as well ?

**Comment by lucasgautheron** [comment]
Note to myself:

> Note: the parser doesn't comply with the entire CHAT file specification. It implements a subset of the specification (enough to parse the SEEDLings corpus).

(pyclan's README)

**Comment by alecristia** [comment]
> @alecristia do you want that in the first release as well ?

if we can, that would be awesome - but not sure how much time it'd take...

**Comment by lucasgautheron** [comment]
Well, it depends. If I could use pyclan, that would probably not take so long. But they say their implementation is not complete, so we might lose information. However, we already make strong assumptions about the inputs, so it would still make sense.

**Comment by lucasgautheron** [comment]
@sarpu, I have tried to use the pyclan package (https://github.com/SeedlingsBabylab/pyclan) on the following file : https://gin.g-node.org/LAAC-LSCP/vandam-data/src/master/annotations/cha/raw/BN32_010007.cha

But it failed with the following errors :

```python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyclan import ClanFile
>>> cha = ClanFile('BN32_010007.cha')
Parser Error:
            index: 13
            line: @Comment:	For the "group" field of the Target_Child, identify (if

            Additional Info: 
Traceback (most recent call last):
  File "/Users/acristia/anaconda3/lib/python3.7/site-packages/pyclan/parse.py", line 159, in parse_file
    raise errors.ParseError(index, last_line)
pyclan.errors.ParseError: Parser Error:
            index: 13
            line: @Comment:	For the "group" field of the Target_Child, identify (if

            Additional Info: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/acristia/anaconda3/lib/python3.7/site-packages/pyclan/clanfile.py", line 48, in __init__
    self.line_map = self.parse_file(flattenedlines, breaks)
  File "/Users/acristia/anaconda3/lib/python3.7/site-packages/pyclan/parse.py", line 257, in parse_file
    raise errors.ParseError(index, last_line)
pyclan.errors.ParseError: Parser Error:
            index: 13
            line: @Comment:	For the "group" field of the Target_Child, identify (if

            Additional Info: 
>>> 
```
Do you have any idea what's causing this issue ?
