### ISSUE TITLE
merge-annotations improvements

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#173]
**Is your feature request related to a problem? Please describe.**

 - what about range_onset/range_offset and time_seek ? currently, not handled carefully either (this is very important!)
 - package_version should be computed carefully.
 - raw_filename does not contain information about the original sets that were combined. (not so bad)
 
**Describe the solution you'd like**

 - set time_seek to 0
 - set range_onset and range_offset to the intersection of the ranges covered by merged set
 - set package_version to the list of the versions involved (comma separated) ? Though, the regex will need to be updated.
 - drop raw_filename or keep it this way

**Comment by LoannPeurey** [comment]
#396
- package version is kept to the version that does the merge : package versions of the merged set can be traced back
- added a column `merged_from` containing the name of the merged sets, that way, we can find back the versions and warn the user when importing/deleting/renaming a set that was used for a merge that he should update/check/re-merge the set.
