### ISSUE TITLE
problems removing datasets (open issue to log behavior)

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildProject#198]
I think maybe I'm not doing everything right in terms of how I install datasets. In a discussion (#188), I documented being unable to remove a dataset, and not even being able to rm -rf * it.

Valentin also had problems removing one of his too. Here's a screenshot of what he was getting:
![Untitled](https://user-images.githubusercontent.com/7464861/117448267-d289a000-af3e-11eb-9def-253552306c68.jpeg)

I think the situation for him was different: I was getting errors about hidden files and annex pointers, whereas he was getting errors about recursive datasets, even after adding --recursive. (He also tried --recursive at the end of his command.)

We don't know what we're doing wrong, but I'm opening an issue in the hope that we'll keep track of how datasets are installed, so we may find a pattern.

**Comment by lucasgautheron** [comment]
Try:

```bash
datalad remove -d EL1000-metrics -r
```
