### ISSUE TITLE
Proper logging

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#232]
**Is your feature request related to a problem? Please describe.**

The use of printf everywhere getting messy and unclear

**Describe the solution you'd like**

https://stackoverflow.com/questions/42388844/where-to-configure-logging

**Comment by MichaBiriuchinskii** [comment]
I've seen a lot of similar cases, so I want to add some information how to handle them here. 

Let's say, we have the following code : 

_proc = subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE) #on lance la commande définit dans args, on dit qu'on n'a pas besoin de stdout, et s'il y a quelque erreur, on print cela
(stdout, stderr) = proc.communicate()
success = proc.returncode == 0
if not success:
   print(stderr, file=sys.stderr)_
   
 To turn the print into a logger, we simply need to refer to the variable, without any extra parameters : 
 **logger_annotations.error(stderr)**
