### ISSUE TITLE
minor changes to doc: getting large data

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildProject#275]
**Is your feature request related to a problem? Please describe.**
https://childproject.readthedocs.io/en/latest/reuse.html#downloading-large-files
is underinformative

**Describe the solution you'd like**
https://childproject.readthedocs.io/en/latest/reuse.html#downloading-large-files has a title that leads me to believe that I'll need to do this only for large files, when in fact many files are by default like this, even when they are small.
Let's rename the section and explain that "by default, many files are just pointers" then give the explanation that is there. Then have a subsection for downloading large files where we recommend the -J switch

**Comment by LoannPeurey** [comment]
7d64b9d
