### ISSUE TITLE
One conda environment to rule them all

### ISSUE THREAD

**Issue by MarvinLvn** [LAAC-LSCP/ChildProject#315]
Installation instructions such as found in the [readthedocs](https://childproject.readthedocs.io/en/latest/install.html) seem a bit complicated. You have instructions for both conda users and non-conda users, admin users and non-admin users.

In other words, there are multiple paths for installing the package and its dependencies depending on your profile. That makes it hard for users to 1) follow the path they have to follow 2) you debugging installation depending on what users understood from the instructions

Would it be possible to provide an environment.yml ([example here](https://github.com/MarvinLvn/voice-type-classifier/blob/new_model/vtc.yml)) so that users just have to run :

```
conda env create -f datalad.yml
conda activate datalad
```

This way, you'd make sure users don't have access rights problem and have all of the required dependencies installed.
For instance, the doc says : 

![Screenshot from 2021-10-20 12-08-39](https://user-images.githubusercontent.com/11290637/138074024-25c1e1e6-763b-4b51-ae23-837f5acd3e32.png)

This can be specified in the .yml file and you could get rid of that note.

**Comment by MarvinLvn** [comment]
On second thought, why not something like : 

```
git clone git@github.com:LAAC-LSCP/ChildProject.git
conda env create -f env_linux.yml 
conda activate childproject
pip install .
```
no need for wget and curl

**Comment by lucasgautheron** [comment]
> Seems to work but :
> 
> * the wget command returns the html code of the page, not the file. (you might want to use curl ? although that means installing curl T_T)
> * the command `pip install ChildProject` should be moved to the .yml file and removed from the instructions
> 
> Something like this should work :
> 
> ```
> name: childproject
> channels:
>   - conda-forge
>   - defaults
> dependencies:
>   - python=3.7
>   - ffmpeg
>   - git-annex>=8.2
>   - pip
>   - pytest
>   - sox
>   - pip:
>     - scipy
>     - ChildProject
> ```
> 
> EDIT : you may want to specify version for git-annex

Of course! Sorry about that;

**Comment by lucasgautheron** [comment]
> On second thought, why not something like :
> 
> ```
> git clone git@github.com:LAAC-LSCP/ChildProject.git
> conda env create -f env_linux.yml 
> conda activate childproject
> pip install .
> ```
> 
> no need for wget and curl

I like to use pypi (because of version management and all);
But I guess one could still do:

```
brew install git-annex
git clone git@github.com:LAAC-LSCP/ChildProject.git --depth 1 -b master
conda env create -f env_macos.yml 
conda activate childproject
pip install ChildProject
```
