### ISSUE TITLE
Adding VTC annotations to eaf-builder

### ISSUE THREAD

**Issue by marianne-m** [LAAC-LSCP/ChildProject#333]
**Is your feature request related to a problem? Please describe.**
The eaf-builder doesn't have an option to import the VTC annotations.
This option would simplify and speed up the annotation work for more complex tasks like VCM or MSC.
Instead of annotating the segment AND do the second task, the annotator would only have to correct the VTC annotation (if necessary) and could focus more on the second task.

**Describe the solution you'd like**
Adding a `--import-vtc-annotations` option to eaf-builder

**Comment by lucasgautheron** [comment]
Just thinking about this more generally, maybe we should have an option to pre-fill the eaf from any kind of annotation ?

**Comment by alecristia** [comment]
tagging this to talk it over tomorrow!

**Comment by lucasgautheron** [comment]
Alright! Just did some un-tested, very preliminary work here: #334

**Comment by lucasgautheron** [comment]
Should now be working with LENA annotations too!
