### ISSUE TITLE
Import any type of EAF tier

### ISSUE THREAD

**Issue by William-N-Havard** [LAAC-LSCP/ChildProject#343]
**Is your feature request related to a problem? Please describe.**
For future annotation campaigns, we might want to create new types of EAF tiers (such as we did to annotate morpho-syntactic complexity). We would like to be able to import the annotations of these new tiers into ChildProject

**Describe the solution you'd like**
Allow the user to specify which tiers should be imported when importing the annotations from an EAF file

**Comment by lucasgautheron** [comment]
The package supports custom converters (cf. https://childproject.readthedocs.io/en/latest/api-annotations.html#custom-converter)

Would this work for you?
