### ISSUE TITLE
Documentation: specify that GIN repositories should be created empty

### ISSUE THREAD

**Issue by William-N-Havard** [LAAC-LSCP/ChildProject#358]
Section _Converting a dataset_ > _Publish to GIN_ > _Point 1_

Update the documentation so as to specify that GIN repositories should be created _empty_. Some interns initiated their GIN repository with a README.md and LICENCE.md file and were unable to push afterwards... and could not figure out what the problem was.

**Comment by LoannPeurey** [comment]
[7def324](https://github.com/LAAC-LSCP/ChildProject/commit/7def32424ab57d2253780e0314a93c407e5a1418)
Added instruction to uncheck "Initialize this repository with selected files and template" and added a screenshot with the steps to follow.
https://childproject.readthedocs.io/en/latest/vandam.html#publish-to-gin
