### ISSUE TITLE
Store version of annotation tools used to ensure reproducibility

### ISSUE THREAD

**Issue by William-N-Havard** [LAAC-LSCP/ChildProject#359]
**Is your feature request related to a problem? Please describe.**
Marvin's VTC annotator has already gone through two versions (one in December 2019 and one in March 2020, see `master` branch and `new_model` branch [here](https://github.com/MarvinLvn/voice-type-classifier/tree/new_model)). 

Some subsequent tools such as ALICE depend on the version of the VTC to produce the appropriate results (using either one set of [regression coefficients](https://github.com/orasanen/ALICE/blob/new_diarizer/regress_ALUCs.py#L13) or [another](https://github.com/orasanen/ALICE/blob/new_diarizer/regress_ALUCs.py#L18)). With new versions of the VTC and ALICE coming out in the next few weeks/months, it appears essential to keep the information of which versions of the tools were used to annotate the audio files. This would prevent us from running tool B with annotations of tool A _v1_ when tool B needs annotations produced by tool A _v2_. For example, ALICE's regression coefficients were tuned so as to compensate for the VTC's errors, it's thus essential to run ALICE with the same VTC segments it was trained on.

**Describe the solution you'd like**
Add a column akin to CP's package_version column so that we can specify the version of the annotation tool used (or commit hash)

**Comment by lucasgautheron** [comment]
Great idea!

Those could be stored in `metadata/annotations.csv` indeed, but maybe also inside the annotation folder? e.g. in some yml file into `annotations/vtc/`? whatever you like better!

**Comment by William-N-Havard** [comment]
I think it would be better if it's stored in `metadata/annotations.csv`. I'm however not sure how to properly signal version numbers. For example, both the VTC and ALICE do not use version numbers (AFAIK), and using the repository's commit hash might be a bit too restrictive (you could apply some cosmetic changes on some files without changing the model itself).

I'm not sure what is the way to go, even though I feel it's an important issue.

**Comment by lucasgautheron** [comment]
I think commit hashes are good because you can always perform a diff between two commit hashes and assess whether the changes are significant.

This raises the broader issue of storing custom metadata about the annotations (for instance, this might be useful for handling manual annotations too -- for instance, one might want to keep track of each annotator's native language). We could just allow users to add their own custom fields to the annotations index and it would be up to them to decide how to handle this.

**Comment by William-N-Havard** [comment]
@alecristia what do you think about this?

**Comment by LoannPeurey** [comment]
We think opening the possibility for people to add whatever column they want to `metadata/annotations.csv` will lead to information not being easily human readable and people will forget it is here. In general `metadata/annotations.csv` should not be open and read by hand.
We believe this information belongs  in an annotation dedicated section in the README of the dataset.
The hash commit of ALICE / VTC should probably be indicated in the README also.
