### ISSUE TITLE
CHA importation fails when CHA file is empty

### ISSUE THREAD

**Issue by William-N-Havard** [LAAC-LSCP/ChildProject#366]
**Is your feature request related to a problem? Please describe.**
CHA importation fails when CHA file contains no transcription (e.g. https://sla.talkbank.org/TBB/phon/Eng-NA/Providence/Alex/010700.cha).

```
'Traceback (most recent call last):\n  File "/scratch2/whavard/PACKAGES/ChildProject/ChildProject/annotations.py", line 432, in _import_annotation\n    df = converter.convert(path, filter, **params)\n  
File "/scratch2/whavard/PACKAGES/ChildProject/ChildProject/converters.py", line 611, in convert\n    df["transcription"] = df.apply(\n  File "/scratch2/whavard/.conda/envs/LSFER/lib/python3.9/site-packages/panda
s/core/generic.py", line 5487, in __getattr__\n    return object.__getattribute__(self, name)\nAttributeError: \'DataFrame\' object has no attribute \'str\'\n'
```

**Describe the solution you'd like**
Check whether https://github.com/LAAC-LSCP/ChildProject/blob/master/ChildProject/converters.py#L626 returns an empty DataFrame or not. If so, create an empty annotation file to show a CHA file exists for this recording but that it contains no useful information.

**Comment by LoannPeurey** [comment]
#379 
The cha converter now return an empty DataFrame if the file is empty.
From there, the conversion goes through and creates an empty converted annotation file
