### ISSUE TITLE
CHA importation: missing transcriptions!

### ISSUE THREAD

**Issue by William-N-Havard** [LAAC-LSCP/ChildProject#367]
I noticed that when importing CHA files for which the speakers' segments are misaligned (i.e. one segment includes the utterances of several speakers), this is not reflected in the imported annotations. **That means that some transcriptions are discarded!**

Take for example [this file](https://sla.talkbank.org/TBB/phon/Eng-NA/Providence/Alex/010427.cha) for which we have two sentences belonging to two speakers that belong -- even though they shouldn't -- to the same segment (from 0s to 7.830s)

```
[1] OPE: where do you want me to go ? ▶
[2] MOT: anywhere you'll feel comfortable &-um (.) anywhere .
```

The imported segments look like that
```
0                        where do you want me to go ?   
1                              please don't do that . 
```

and more specifically the first segment only contains

```
transcription                              where do you want me to go ? 
mor                    pro:int|where mod|do pro:per|you v|want pro:ob...
gra                    1|4|JCT 2|4|AUX 3|4|SUBJ 4|0|ROOT 5|4|OBJ 6|7|...
pho                                                                  NaN
mod                                                                  NaN
sit                                                                  NaN
com                                                                  NaN
segment_onset                                                          0
segment_offset                                                      7830
speaker_id                                                           OPE
speaker_role                                                Investigator
speaker_type                                                         NaN
words                                                                  7
raw_filename                                        Alex/Alex_010427.cha
set                                                                  cha
recording_filename                                  Alex/Alex_010427.wav
time_seek                                                              0
range_onset                                                            0
range_offset                                                     3366963
format                                                               cha
filter                                                               NaN
annotation_filename                       Alex/Alex_010427_0_3366963.csv
imported_at                                          2022-03-02 15:00:03
package_version                                                    0.0.4
error                                                                NaN
Name: 0, dtype: object
```

That is, this segment only contains the transcription of what OPE said but not of what MOT said. This is particularly problematic as 1) we are missing some annotations (which are then used elsewhere: reliability metrics, etc.) and 2) this would be useful to know which alignments are faithful (e.g. 1 sentence for 1 speaker) from alignments that aren't!

**Comment by alecristia** [comment]
I'm afraid there is nothing we can do about this... The heart of ChildProject is in time-stamped annotations, so we need time stamps.

The only alternative I see is taking the step between the last offset and the next offset and dividing that by the number of utterances without time stamps in equal portions. But then we'd need a marker at the utterance level telling us that these are assigned onset/offset times...

**Comment by William-N-Havard** [comment]
I agree that the time-stamped annotations are really important! However, I think it is important to mention in the documentation that non-aligned annotations will be discarded. I thought the annotations were imported "as is" and not that some would be discarded, and I guess I'm not the only one. I may have sometimes used the CHA annotations imported in CP as I wouldn't have the extra hurdle of processing them myself, if I had known some were missing I wouldn't have.

An in-between step would be importing all annotations and using NA for those missing timestamps. We'd simply have to remove [this line](https://github.com/LAAC-LSCP/ChildProject/blob/master/ChildProject/converters.py#L674) and filter annotations with "NA" tags when there are used (e.g. reliability metrics). That way, this allows the user to have access to all annotations (and see whether the timestamps are trustworthy are not) without hindering the normal use of CP.

**Comment by alecristia** [comment]
good point, we should have a disclaimer! I'm not 100% certain about importing all lines and giving NA tags for time stamps, as this would pervert many of the analyses that are done.

Perhaps a better thing to do in the future is, at least for public CHILDES corpora, to think of how those time stamps can be improved via citizen scientists / students reannotating them. This is quite a massive enterprise though, so we can think of it rather as a potential grant to write!
