### ISSUE TITLE
Template command

### ISSUE THREAD

**Issue by William-N-Havard** [LAAC-LSCP/ChildProject#371]
It would be great to create a CLI command so as to create an empty project with all the necessary directories and files.

For example, such a command (e.g. `child-project template`) would create:
 - `annotations`, `recordings/raw`, `metadata`, `scripts`, and `extra` directories
 - `children.csv` and `recordings.csv` created with the required columns

That way, one would only have to place the data in the required directories and fill in the CSV files without having to check which columns are required

**Comment by alecristia** [comment]
hi,
I wonder, how is this different from datalad procedures: https://github.com/LAAC-LSCP/datalad-procedures?
It may be the same -- in which case that means our documentation needs to be improved to highlight this!!
-a

**Comment by William-N-Havard** [comment]
It is exactly the same indeed! I couldn't find any reference to this point in the documentation though

**Comment by LoannPeurey** [comment]
We are building a 'creating a new dataset' page in the lab [handbook](https://laac-lscp.github.io/docs/create-a-new-dataset.html) where we reference the datalad-procedures.

Should we also have a reference for it in the childproject doc (knowing that this is not strictly speaking a childproject feature)? and if so, where?

**Comment by LoannPeurey** [comment]
- tutorial for creating from scratch
- dataset structure
