### ISSUE TITLE
Free recording_device_type format

### ISSUE THREAD

**Issue by William-N-Havard** [LAAC-LSCP/ChildProject#391]
Currently, recording_device_type is limited to lena, usb, olympus, babylogger, and unknown. 

However, data may be collected using other devices than those listed (e.g. phone with Whatsapp) and it would be good to let the user specify the correct value rather than forcing them to choose one that would be either erroneous or non-informative (e.g. unknown).

**Comment by LoannPeurey** [comment]
Do we know why it was originally implemented that way? There probably was a reason to restrict the range of accepted values.

**Comment by LoannPeurey** [comment]
It will probably be more interesting to extend the list rather than allow for any value. Allowing for grouping 'by device'
