### ISSUE TITLE
Merge set order

### ISSUE THREAD

**Issue by William-N-Havard** [LAAC-LSCP/ChildProject#398]
**Is your feature request related to a problem? Please describe.**
When merging two sets, a new column is added `merged_from` which indicates which sets were used. This column contains the name of the two sets (left set and right set), separated by a comma. The order in which the two sets appear changes from one run to another (e.g. 'vtc,alice' or 'alice,vtc') even when nothing is changed. 

**Describe the solution you'd like**
It would be better to keep the order consistent so that it reflects which set was the left set and which was the right set.

**Comment by LoannPeurey** [comment]
#399 
The order is now always left_set,right_set
