### ISSUE TITLE
validate fails with broken symlinks

### ISSUE THREAD

**Issue by LoannPeurey** [LAAC-LSCP/ChildProject#425]
**Is your feature request related to a problem? Please describe.**
Currently the `child-project validate` command either requires all the recordings to be downloaded or does not check anything related to recordings (`--ignore-recordings`) but very often, we have broken symlinks present as the dataset was cloned from gin with datalad without downloading the actual recordings.

**Describe the solution you'd like**
A broken symlink should output a warning rather than an error, or have an option `--symlinks-recordings` to accept broken symlinks for recordings

**Comment by LoannPeurey** [comment]
Leaning towards having just a warning in case of not present recording(s)

**Comment by MichaBiriuchinskii** [comment]
In project.py 

 there's a condition if which checks wether the file is ok. 

insert in this line https://github.com/LAAC-LSCP/ChildProject/blob/e284d2b7a2da6621f91ad613b45b5ad685cf0201/ChildProject/projects.py#L542
Smth like 'elif path == BROKEN_SEMILINKS.... 
message = .... f"cannot find recording '{raw_filename}' at '{path}'"
self.warnings.append(message)
continue 



Than, to test it, I'll have to create a broken simlink.
