### ISSUE TITLE
Zooniverse upload tracking

### ISSUE THREAD

**Issue by LoannPeurey** [LAAC-LSCP/ChildProject#427]
**Is your feature request related to a problem? Please describe.**
When uploading to zooniverse, the update of the csv for all clips is done only at the end, resulting in largely successful uploads not being recorded as such because 1 down the line failed, then the csv is to be updated manually to record those successful uploads.

**Describe the solution you'd like**
Make it so that an occurring error will still allow the program to save the csv and then exit.

**Comment by khitczenko** [comment]
It works well for this error:
failed to save chunk 181742. an exception has occured:
Validation failed: Locations is invalid
panoptes_client.panoptes.PanoptesAPIException: Validation failed: Locations is invalid

But runs into trouble for this error: 
panoptes_client.panoptes.PanoptesAPIException: Attempted to update a stale object: SubjectSet.

**Comment by LoannPeurey** [comment]
Maximum uploaded subject amount error should not allow for continuing the upload even with the ignore errors flag as it is clear everything from that point on will fail.

failed to save chunk 29736. an exception has occured:
User has uploaded 253382 subjects of 250000 maximum
Traceback (most recent call last):
  File "/scratch2/lpeurey/conda/childproject/lib/python3.7/site-packages/ChildProject/pipelines/zo
oniverse.py", line 450, in upload_chunks
    subject.save()

**Comment by LoannPeurey** [comment]
We may want to secure the writing of the csv to complete even in extrene cases (eg SIGTERM), this is done by either writing periodically or handling termination signals / keyboard interruptions etc

**Comment by LoannPeurey** [comment]
#405 should be implemented as well

**Comment by LoannPeurey** [comment]
regarding orphan subject, this thread is relevant : https://github.com/zooniverse/panoptes/issues/1529

**Comment by LoannPeurey** [comment]
The chunks csv file does record the subject set name but not the id. The name is susceptible to change and the id is not and easier to match and get , so we should record it, probably in addition to name to keep backwards compatibility
