### ISSUE TITLE
eaf-builder import annotations speaker_id NA

### ISSUE THREAD

**Issue by LoannPeurey** [LAAC-LSCP/ChildProject#438]
**Is your feature request related to a problem? Please describe.**
The eaf-builder when used with import-annotations is trying to use the speaker_id to give a tier name, and if speaker_id does not exist, uses speaker_type.
But a rpoblem arises if speaker_id exists but is NA, as the NA value will be used for the tier name instead of trying to use speaker_type

**Describe the solution you'd like**
check that speaker_id exists and is not null before using it to name the tier

**Comment by LoannPeurey** [comment]
https://github.com/LAAC-LSCP/ChildProject/blob/e284d2b7a2da6621f91ad613b45b5ad685cf0201/ChildProject/pipelines/eafbuilder.py#L68

to be replaced by :
```python
if "speaker_id" in segment and not pd.isnull(segment["speaker_id"]):
```

**Comment by MichaBiriuchinskii** [comment]
1. I have to create a branch
3. I have to commit the changes
4. I have to run the tests 
5. Create the pull request
