### ISSUE TITLE
Documentation metadata

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#71]
Some columns might be impossible to standardize because they're too project specific. But they should be documented nonetheless !

One way to do that would be to require unknown columns (those that are not 'standards') to be referenced and documented into a dataframe called `metadata/docs.csv` or something.

What do you think ?

**Comment by alecristia** [comment]
we should add to standard cols:

- nae = whether the child is learning north-american english (USA/Canada) = TRUE/T/1 or not = FALSE/F/0
